# render.yaml â€” Blueprint para deploy no Render
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: datathon-grupo-179
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/valdrei/datathon-fase5-grupo-179
    branch: main
    plan: free
    envVars:
      - key: API_URL
        value: http://localhost:8000
      - key: PORT
        value: "10000"
    healthCheckPath: /
    buildFilter:
      paths:
        - app/**
        - src/**
        - frontend/**
        - Dockerfile
        - requirements.txt
